services:
  - type: web
    name: puppets-corner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn puppetscorner.wsgi:application
    workingDir: backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: puppetscorner.settings