# Generated by Django 5.2 on 2025-06-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestMessages', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='profile_image_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
