# Generated by Django 5.2 on 2025-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestMessages', '0003_message_profile_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
