# Generated by Django 5.2 on 2025-07-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestMessages', '0004_statusmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='name',
            field=models.CharField(choices=[('Puppet', 'Puppet'), ('Lolo', 'Lolo')], max_length=100),
        ),
    ]
