# Generated by Django 5.2 on 2025-07-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestMessages', '0005_alter_statusmessage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='profile_image_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
